SurveyApp/Controllers/ChildController.cs
using Newtonsoft.Json;
using SurveyApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace SurveyApp.Controllers
{
    [Authorize]
    public class ChildController : Controller
    {
        //
        // GET: /Child/
        public ChildController() {         
            Database.SetInitializer<StudyContext>(null);
            Database.SetInitializer<Child_Survey_ScheduleContext>(null);
            Database.SetInitializer<Child_Study_RespondentContext>(null);
            Database.SetInitializer<ScheduleReminderContext>(null);
            Database.SetInitializer<ConsentContext>(null);
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ChildAddEdit(int? id)
        {
            ViewData["dsParents"] = DataHelper.Parent_GetAll();
            Child objChild = new Child();
            if (id.HasValue)
            {
                var cContext = new ChildContext();
                objChild = cContext.Children.Find(id);
            }

            return View(objChild);
        }

        [HttpPost]
        public ActionResult ChildAddEdit(Child childModel, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View(childModel);
            }
            try
            {
                if (childModel.Gender == 0)
                {
                    ModelState.AddModelError("", "Please select gender.");
                    return View(childModel);
                }

                if (childModel.StatusId == 0)
                {
                    ModelState.AddModelError("", "Please select enrollment status.");
                    return View(childModel);
                }
                if (childModel.Consent == true)
                {
                    if (String.IsNullOrEmpty(childModel.Email))
                    {
                        ModelState.AddModelError("", "Please provide email address for consent.");
                        return View(childModel);
                    }
                }

                if(childModel.Account == true && childModel.Id <= 0)
                {
                    if (String.IsNullOrEmpty(collection["regEmail"]))
                    {
                        ModelState.AddModelError("", "Please provide email address for student account.");
                        return View(childModel);
                    }
                    if (String.IsNullOrEmpty(collection["regPassword"]))
                    {
                        ModelState.AddModelError("", "Please provide password for student account.");
                        return View(childModel);
                    }
                    if (String.IsNullOrEmpty(collection["regConfirmPassword"]))
                    {
                        ModelState.AddModelError("", "Please provide confirm password  for student account.");
                        return View(childModel);
                    }
                    if (String.IsNullOrEmpty(collection["regPassword"]) == false && String.IsNullOrEmpty(collection["regConfirmPassword"]) == false)
                    {
                        if(collection["regPassword"].ToString() != collection["regConfirmPassword"].ToString())
                        {
                            ModelState.AddModelError("", "Both passwords do not match for student account.");
                            return View(childModel);
                        }
                    }
                }

                int studyCount = 0;
                foreach (var key in collection.Keys)
                {
                    if (key.ToString().Contains("StudyId_") && key.ToString().StartsWith("StudyId_"))
                    {
                        studyCount++;
                    }
                }
                if (studyCount == 0)
                {
                    ModelState.AddModelError("", "Please select at least one study.");
                    return View(childModel);
                }

                int teacherCount = 0;
                foreach (var key in collection.Keys)
                {
                    if (key.ToString().Contains("TeacherId_"))
                    {
                        teacherCount++;
                    }
                }
                //if (teacherCount == 0)
                //{
                //    ModelState.AddModelError("", "Please select at least one teacher.");
                //    return View(childModel);
                //}


                if(childModel.Id <= 0 && doesChildExist(childModel.Name, childModel.dob))
                {
                    ModelState.AddModelError("", "This child already exists in the system, please provide different details.");
                    return View(childModel);
                }

                int cId = 0;
                DateTime? dtEnrollment = null;
                Child objChild = new Child();
                int accountId = 0;
                
                using (var cContext = new ChildContext())
                {                    
                    if (childModel.Id > 0)
                    {
                        objChild = cContext.Children.Find(childModel.Id);
                        if (objChild.StatusId != childModel.StatusId)
                        {
                            DataHelper.child_updateStatus(objChild.Id, childModel.StatusId, DateTime.Now, WebSecurity.CurrentUserName);
                        }
                    }

                    objChild.Name = childModel.Name;
                    objChild.dob = childModel.dob;
                    objChild.Gender = childModel.Gender;
                    objChild.ParentId = childModel.ParentId;
                    objChild.SchoolId = childModel.SchoolId;
                    objChild.StatusId = childModel.StatusId;

                    

                    if (childModel.StatusId == 1 && objChild.EnrollmentDate == null)
                    {
                        objChild.EnrollmentDate = DateTime.Now;
                    }
                    if (childModel.Id <= 0)
                    { 
                        if (childModel.StatusId != 1)
                        { 
                            objChild.EnrollmentDate = null;
                        }
                    }
                    objChild.Consent = childModel.Consent;                    
                    
                    objChild.Account = childModel.Account;

                    dtEnrollment = objChild.EnrollmentDate;

                    if (childModel.Id <= 0)
                    {
                        objChild.Agreed = false;
                        cContext.Children.Add(objChild);
                    }

                    if (String.IsNullOrEmpty(childModel.Email) == true && String.IsNullOrEmpty(objChild.Email) == true)
                    {
                        objChild.Email = String.IsNullOrEmpty(collection["regEmail"]) == false ? collection["regEmail"] : "";
                    }

                    if (String.IsNullOrEmpty(objChild.Email) == false)
                    {
                        accountId = WebSecurity.GetUserId(objChild.Email);
                    }

                    cContext.SaveChanges();
                    cId = childModel.Id > 0 ? childModel.Id : cContext.Children.Max(item => item.Id);
                    childModel.EnrollmentDate = dtEnrollment;
                    if (childModel.Id < 0)
                    {
                        DataHelper.child_updateStatus(cId, objChild.StatusId, DateTime.Now, WebSecurity.CurrentUserName);
                    }

                    if(childModel.Account == true && childModel.Id <= 0)
                    {
                        string role = "Student";
                        string email = String.IsNullOrEmpty(collection["regEmail"]) == false ? collection["regEmail"] : "";
                        string pass = String.IsNullOrEmpty(collection["regPassword"]) == false ? collection["regPassword"] : ""; ;

                        if(email != "" && pass != "")
                        {
                            RegisterModel reg = new RegisterModel();
                            reg.FullName = childModel.Name;
                            reg.UserName = email;
                            reg.Password = pass;
                            AccountController.CreateAccount(reg, role);
                            accountId = WebSecurity.GetUserId(email);
                        }                        
                    }
                }

                    #region Child_Study_Respondents
                    List<Study> lstStidues = Study.StudyGetAll();
                    List<Child_Study_Respondent> lstCSRPrevious = new List<Child_Study_Respondent>();
                    DataSet dsTeachers = Child_Teacher.Child_TeacherGetAll();
                    using (var csrConext = new Child_Study_RespondentContext())
                    {
                        lstCSRPrevious = csrConext.Child_Study_Respondents.Where(csr => csr.ChildId == cId).ToList();
                        csrConext.Child_Study_Respondents.RemoveRange(csrConext.Child_Study_Respondents.Where(csr => csr.ChildId == cId));
                        csrConext.SaveChanges();
                        csrConext.Dispose();
                    }

                    List<Consent> lstConsents = new List<Consent>();
                    using (var csrConext = new Child_Study_RespondentContext())
                    {
                        foreach (Study objStudy in lstStidues)
                        {
                            int conId = 0;
                            if (!String.IsNullOrEmpty(collection["StudyId_" + objStudy.Id]))
                            {

SurveyApp/Views/Child/Index.cshtml
@using System.Data;
@{
    ViewBag.Title = "eBit - Child Manager";
    Layout = "~/Views/Shared/_Layout.cshtml";

    DataSet dsChildren = SurveyApp.DataHelper.ChildGetAll();
}


<style type="text/css">
    .ui-tooltip {
        min-width: 200px;
        max-width: 400px;
        background-color: #333;
        color: #FFF;
    }
    #tblChildren .name{
        text-transform: capitalize;
    }
    #tblChildren .text-success {
        color: #33b86c;
    }
    #tblChildren .text-danger {
        color: #ef5350;
    }
</style>

<script type="text/javascript">
    $(function () {
        $("#tblChildren").DataTable({ dom: 'Bfrtip', buttons: [{ extend: 'excel', text: "Export to Excel", title: 'Children_List', exportOptions: {  modifier: { search: 'none', order: 'original' }} }], "oLanguage": { "sInfo": "Displaying _START_ to _END_ of _TOTAL_ Children" } });
        });
</script>
<div>
    <h2 class="col-sm-11" style="margin: 0px;padding: 0px;">Child Manager</h2>
    <a href="@Url.Action("ChildAddEdit", "Child")" class="btn btn-default" style="float:right;"><i class="fa fa-child"></i>&nbsp;Add Child</a>
</div>
<div style="clear:both;"></div>
<br />
<style>
    .table-hover tbody tr{cursor:pointer;}
</style>
<table class="table table-striped table-hover" id="tblChildren">
    <thead>
        <tr>
            <th>Name</th>
            <th>DOB</th>
            <th>School</th>
            <th>Parent</th>
            <th>Teacher(s)</th>
            <th>Study(s)</th>
            <th>Status</th>
            @*<th style="width: 50px;">Consent</th>*@
            <th style="width: 50px;">Action</th>
        </tr>
    </thead>
    <tbody>
        @if (dsChildren != null && dsChildren.Tables.Count > 0 && dsChildren.Tables[0] != null && dsChildren.Tables[0].Rows.Count > 0)
{
    foreach (DataRow dr in dsChildren.Tables[0].Rows)
    {
        <tr onclick="location.href = '@Url.Action("ChildAddEdit", "Child", new { id = dr["Id"] })';">
            <td title="@(dr["IsSelfRespondent"] != DBNull.Value && Convert.ToBoolean(dr["IsSelfRespondent"]) == true ? "This child is self respondent" : "")" data-toggle="@(dr["IsSelfRespondent"] != DBNull.Value && Convert.ToBoolean(dr["IsSelfRespondent"]) == true ? "tooltip" : "")" class="name">@(dr["Name"])<label class="text-danger">@(dr["IsSelfRespondent"] != DBNull.Value && Convert.ToBoolean(dr["IsSelfRespondent"]) == true ? "*" : "")</label></td>
            <td>@(dr["dob"] != DBNull.Value ? Convert.ToDateTime(dr["dob"]).ToString("MM/dd/yyyy") : "")</td>
            <td class="name">@dr["School"]</td>
            <td class="name">@dr["Parent"]</td>
            <td class="name">@dr["Teacher"]</td>
            <td class="name">@dr["Study"]</td>
            <td><a href="javascript:void(0);" onclick="event.stopPropagation();showStatusHistory(this, @dr["Id"], '@dr["Name"]');" class="@((int)dr["StatusId"] == 1 ? "text-success" : "text-danger")">@SurveyApp.Controllers.ChildController.getStatusDescription((int)dr["StatusId"])</a></td>
            @*<td style="text-align: center;vertical-align:middle;">
                    @if(dr["Consent"] != DBNull.Value && Convert.ToBoolean(dr["Consent"]) == true){
                        <i class="ion-eye @(dr["Consent"] != DBNull.Value && Convert.ToBoolean(dr["Consent"]) == true ? (dr["Agreed"] != DBNull.Value ? (Convert.ToBoolean(dr["Agreed"]) == false ? "redeye" : "greeneye") : "redeye") : "")"  data-toggle='tooltip' title="@(dr["Consent"] != DBNull.Value && Convert.ToBoolean(dr["Consent"]) == true ? (dr["Agreed"] != DBNull.Value ? (Convert.ToBoolean(dr["Agreed"]) == false ? "Child has not given consent yet." : "Child has given the consent" + (dr["AgreeDate"] != DBNull.Value ? " on " + Convert.ToDateTime(dr["AgreeDate"]).ToString("MM/dd/yyyy") : ".")) : "") : "Consent is not required for this child.")"></i>
                    }
                </td>*@
            <td style="text-align: center;vertical-align:middle;"><a href="javascript:void(0);" class="redCross" onclick="event.stopPropagation();deleteListItem(this, @dr["Id"], 'child', '@dr["Name"]', function(){ location.reload(true); });"><i class="ion-close"></i></a></td>
        </tr>
    }
}
    </tbody>
</table>

<script type="text/javascript">
    $('[data-toggle="tooltip"]').tooltip({
        track: true,
        content: function () {
            return $(this).attr('title').replace(/_NEWLINE_/g, "<br/>");
        },
    });

    function goToDetailPage(childId, childName, statusId, schoolName) {
        //d
        if (statusId == 1) {
            location.href = '@Url.Action("ChildAddEdit", "Child")?id=' + childId;
        }
        else {
            var statusText = "";
            if (statusId == 2) {
                statusText = " has lost Followup.";
            }
            else if (statusId == 3) {
                statusText = " has withdrew Consent.";
            }
            else if (statusId == 4) {
                statusText = " is no longer at " + schoolName;
            }

            bootbox.dialog({
                message: childName + statusText + "<br/>Do you want to view the details?",
                title: "<span style='text-transform:capitalize;'>" + childName + "</span>",
                closeButton: false,
                onEscape: function() {

                },
                buttons: {
                    success: {
                        label: "Yes",
                        className: "btn-primary",
                        callback: function() {
                            location.href = '@Url.Action("ChildAddEdit", "Child")?id=' + childId;
                        }
                    },
                    danger: {
                        label: "No",
                        className: "btn-default",
                        callback: function() {

                        }
                    }
                }
            });
        }
    }

    function showStatusHistory(elem, childId, childName) {
        $.ajax({
            url: "@Url.Action("GetStatusHistory", "Child")?childId=" + childId,
            dataType: "html",
            success: function (data) {
                if (isSessionValid(data) == true) {                    
                    bootbox.dialog({
                        message: data,
                        size: "large",
                        closeButton: true,
                        title: "<span style='text-transform:capitalize;'>" + childName + "</span> - Status History",
                        onEscape: function() {

                        },
                        buttons: {
                            cancel: {
                                label: 'Close',
                                className: 'btn-default'
                            }
                        }
                    });                    
                }
                checkTimeout(data, 0);
            }
        });
    }
</script>

SurveyApp/Views/Child/_StatusHistory.cshtml
@using SurveyApp.Models;
@using System.Data;

@{    
    int childId = String.IsNullOrEmpty(Request.QueryString["childId"]) != true ? Convert.ToInt32(Request.QueryString["childId"]) : 0;    
    DataSet ds = SurveyApp.DataHelper.Child_GetStatusHistory(childId);

    string childName = string.Empty;
}

<style type="text/css">
    .statusHistory .dt-buttons {
        bottom: 10px;
        position: relative;
    }

    #tblChildStatusHistory_wrapper {
        margin-top: 10px;
    }
</style>

<div class="statusHistory">
    <div class="info" style="border:solid 1px #CCC;padding: 6px;background-color: #FFF;max-height:350px;overflow-y:auto;">
    @if (ds.Tables[0].Rows.Count > 0)
    {
        <table id="tblChildStatusHistory" cellpadding="0" cellspacing="0" style="width:100%;" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Status</th>
                    <th>Changed On</th>
                    <th>Changed By</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow dr in ds.Tables[0].Rows)
                {
                    <tr class="item">
                        <td>@dr["Status"]</td>
                        <td>@dr["Date"]</td>
                        <td>@dr["UserName"]</td>
                    </tr>
                }                
            </tbody>
        </table>
    }
    else
    {
        <div style="text-align:center;">This child's status has never been changed.</div>
    }
    </div>    
</div>